export const APPLICATION_ACTIONS_CONSTS = {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIE: 'GET_MOVIE',
  GET_HALLS: 'GET_HALLS',
  GET_SHOW_TIMES: 'GET_SHOW_TIMES',
  GET_SHOWING_MOVIES: 'GET_SHOWING_MOVIES',
  SET_SPINNING: 'SET_SPINNING',
  GET_SHOW_TIME_DETAILS: 'GET_SHOW_TIME_DETAILS',
  SET_ACTIVE_ORDER: 'SET_ACTIVE_ORDER',
  SET_PORTAL_SETTINGS: 'SET_PORTAL_SETTINGS',
} as const;
