trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  webAppName: '$(AZURE_WEBAPP_NAME)'
  azureSubscription: '$(AZURE_SERVICE_CONNECTION)'

stages:
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: Build_Job
        displayName: 'Build'
        steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          inputs:
            versionSpec: '22.x'
          displayName: 'Install Node.js 22 LTS'

        - task: Cache@2
          inputs:
            key: 'npm | "$(Agent.OS)" | package-lock.json'
            path: 'node_modules'
            cacheHitVar: 'CACHE_RESTORED'
          displayName: 'Cache node_modules'

        - task: Npm@1
          inputs:
            command: 'ci'
          displayName: 'Install dependencies'
          condition: ne(variables.CACHE_RESTORED, 'true')

        - script: |
            echo "Copying production Vite config..."
            if [ -f "$(System.DefaultWorkingDirectory)/vite.config.prod.ts" ]; then
              cp $(System.DefaultWorkingDirectory)/vite.config.prod.ts $(System.DefaultWorkingDirectory)/vite.config.ts
              echo "Production config copied successfully"
            else
              echo "Production config file not found, using default"
            fi
          displayName: 'Set production Vite config'

        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
          displayName: 'Build application'

        - script: |
            echo "Creating web.config for Azure Web App..."
            cat > $(System.DefaultWorkingDirectory)/dist/web.config << 'EOF'
            <?xml version="1.0" encoding="utf-8"?>
            <configuration>
              <system.webServer>
                <rewrite>
                  <rules>
                    <rule name="React Routes" stopProcessing="true">
                      <match url=".*" />
                      <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                      </conditions>
                      <action type="Rewrite" url="/" />
                    </rule>
                  </rules>
                </rewrite>
                <staticContent>
                  <mimeMap fileExtension=".json" mimeType="application/json" />
                  <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
                  <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
                </staticContent>
                <httpErrors existingResponse="PassThrough" />
              </system.webServer>
            </configuration>
            EOF
            echo "web.config created successfully"
          displayName: 'Create web.config for SPA routing'

        - task: ArchiveFiles@2
          displayName: 'Archive build files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'drop'
          displayName: 'Publish artifacts'

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy_Job
        displayName: 'Deploy Web App'
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
          displayName: 'Download build artifacts'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '$(azureSubscription)'
            appType: 'webApp'
            WebAppName: '$(webAppName)'
            packageForLinux: '$(System.ArtifactsDirectory)/drop/$(webAppName).zip'
            enableCustomDeployment: true
            DeploymentType: 'zipDeploy'
            RuntimeStack: 'NODE|22-lts'
          displayName: 'Deploy to Azure Web App'
