trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'  # Adjust this to your Node.js version

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build Vite React app'
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: $(nodeVersion)

    - script: |
        npm ci
        npm install terser --save-dev
      displayName: 'Install dependencies'

    - script: |
        npm run build -- --mode production
      displayName: 'Build Vite React app for production'
      
    - script: |
        cp web.config dist/
        # Create robots.txt for production
        echo -e "User-agent: *\nDisallow: /admin\nAllow: /" > dist/robots.txt
      displayName: 'Copy web.config and create robots.txt'

    - task: CopyFiles@2
      displayName: 'Copy build files to artifact staging directory'
      inputs:
        SourceFolder: 'dist'  # Vite's default output directory
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
        appType: 'webApp'
        appName: '$(AZURE_WEBAPP_NAME)'
        package: '$(System.ArtifactsDirectory)/drop'
        deploymentMethod: 'auto'
