trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: Build_and_Test
    displayName: 'Build and Test React App'
    jobs:
      - job: Build_Test_Job
        displayName: 'Build and Test'
        steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - task: Cache@2
          inputs:
            key: 'npm | "$(Agent.OS)" | package-lock.json'
            path: 'node_modules'
            cacheHitVar: 'CACHE_RESTORED'
          displayName: 'Cache node_modules'

        - task: Npm@1
          inputs:
            command: 'ci'
          displayName: 'Install dependencies'
          condition: ne(variables.CACHE_RESTORED, 'true')

        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run test'
          displayName: 'Run tests'

        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
          displayName: 'Build application'

        - script: |
            echo "Listing directory contents:"
            ls -la $(System.DefaultWorkingDirectory)
            echo "Listing build directory contents:"
            ls -la $(System.DefaultWorkingDirectory)/dist
          displayName: 'Debug directory contents'

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'coverage/junit.xml'
          displayName: 'Publish test results'
          condition: succeededOrFailed()

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
            ArtifactName: 'react-app'
          displayName: 'Publish build artifacts'
