trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Replace with the name of your Azure DevOps service connection
  azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
  # Replace with the name of your Azure Web App
  appName: '$(AZURE_WEBAPP_NAME)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Deploy to Azure Web App'